export const petDummyData = [
    {
        name: "mike",
        sprite: 1,
        age: 0,
        level: 1,
        exp: 0,
        reqExp: 10,
        hungryLevel: 100,
        hungryThreshold: 80,
        isHungry: false,
        sleepyLevel: 100,
        sleepyThreshold: 80,
        isSleepy: false,
        dirtyLevel: 100,
        dirtyThreshold: 80,
        isDirty: false,
        lazyLevel: 100,
        lazyThreshold: 80,
        isLazy: false,
    },
    {
        name: "sam",
        sprite: 1,
        age: 0,
        level: 1,
        exp: 0,
        reqExp: 10,
        hungryLevel: 100,
        hungryThreshold: 80,
        isHungry: false,
        sleepyLevel: 100,
        sleepyThreshold: 80,
        isSleepy: false,
        dirtyLevel: 100,
        dirtyThreshold: 80,
        isDirty: false,
        lazyLevel: 100,
        lazyThreshold: 80,
        isLazy: false,
    }, {
        name: "bee",
        sprite: 1,
        age: 0,
        level: 1,
        exp: 0,
        reqExp: 10,
        hungryLevel: 100,
        hungryThreshold: 80,
        isHungry: false,
        sleepyLevel: 100,
        sleepyThreshold: 80,
        isSleepy: false,
        dirtyLevel: 100,
        dirtyThreshold: 80,
        isDirty: false,
        lazyLevel: 100,
        lazyThreshold: 80,
        isLazy: false,
    },
]


