export const petDummyData = [
    {
        name: "mike",
        sprite: 1,
        age: 0,
        level: 1,
        exp: 0,
        hungryLevel: 0,
        hungryThreshold: 5,
        isHungry: false,
        sleepyLevel: 0,
        sleepyThreshold: 5,
        isSleepy: false,
        dirtyLevel: 0,
        dirtyThreshold: 5,
        isDirty: false,
        lazyLevel: 0,
        lazyThreshold: 5,
        isLazy: false,
    },
    // {
    //     name: "sam",
    //     sprite: 1,
    //     level: 1,
    //     exp: 0,
    //     hungryLevel: 0,
    //     hungryThreshold: 5,
    //     isHungry: false,
    //     sleepyLevel: 0,
    //     sleepyThreshold: 5,
    //     isSleepy: false,
    //     dirtyLevel: 0,
    //     dirtyThreshold: 5,
    //     isDirty: false,
    //     lazyLevel: 0,
    //     lazyThreshold: 5,
    //     isLazy: false,
    // },
    // {
    //     name: "bianca",
    //     sprite: 1,
    //     level: 1,
    //     exp: 0,
    //     hungryLevel: 0,
    //     hungryThreshold: 5,
    //     isHungry: false,
    //     sleepyLevel: 0,
    //     sleepyThreshold: 5,
    //     isSleepy: false,
    //     dirtyLevel: 0,
    //     dirtyThreshold: 5,
    //     isDirty: false,
    //     lazyLevel: 0,
    //     lazyThreshold: 5,
    //     isLazy: false,
    // },
]


