export const petDummyData = [
    {
        name: "Tri",
        sprite: "/sprite1.png",
        level: 1,
        exp: 0,
        reqExp: 10,
        hungryLevel: 100,
        hungryThreshold: 80,
        isHungry: false,
        sleepyLevel: 100,
        sleepyThreshold: 80,
        isSleepy: false,
        dirtyLevel: 100,
        dirtyThreshold: 80,
        isDirty: false,
        lazyLevel: 100,
        lazyThreshold: 80,
        isLazy: false,
    },
    {
        name: "Tom",
        sprite: "/sprite2.png",
        level: 1,
        exp: 0,
        reqExp: 10,
        hungryLevel: 100,
        hungryThreshold: 80,
        isHungry: false,
        sleepyLevel: 100,
        sleepyThreshold: 80,
        isSleepy: false,
        dirtyLevel: 100,
        dirtyThreshold: 80,
        isDirty: false,
        lazyLevel: 100,
        lazyThreshold: 80,
        isLazy: false,
    }, {
        name: "Sam",
        sprite: "/sprite4.png",
        level: 1,
        exp: 0,
        reqExp: 10,
        hungryLevel: 100,
        hungryThreshold: 80,
        isHungry: false,
        sleepyLevel: 100,
        sleepyThreshold: 80,
        isSleepy: false,
        dirtyLevel: 100,
        dirtyThreshold: 80,
        isDirty: false,
        lazyLevel: 100,
        lazyThreshold: 80,
        isLazy: false,
    },
]


